２章実力確認問題
Hiromi0613/java_practice pull request #1
Opened 2024-09-11 08:18 UTC by Hiromi0613

【概要】
2章実力確認問題のコーディングが完了しました。

【内容】
①Hello World!を表示します。
②入力した2つの文字列を結合したHello World!を表示します。
③int型の変数x,yに数値を代入し入れ替えて表示します。
④int型の変数xに７を代入し3倍の値及び半分の値を表示します。

【テスト内容】
[２章_テスト仕様書.xlsx](https://github.com/user-attachments/files/16960291/_.xlsx)

2024-09-12 13:25 UTC, NakaU0209 requested changes
レビューしました！
指摘内容は横展開お願いします！

2024-09-12 13:25 UTC, NakaU0209 commented on Test2/src/test2/Test2_01.java
> +//コンソールに”Hello World!”を表示するプログラムを作成してください
ここにはコメントは書かないようにしましょう！

2024-09-12 13:25 UTC, NakaU0209 commented on Test2/src/test2/Test2_01.java
> +class Test2_01
全体的に以下の修正をお願いします！
・クラスにはpublicをつけましょう！
・クラス、メソッド、メンバ変数にはJavaDocをつけましょう！
　https://qiita.com/maku77/items/6410c67ce95e08d8d1bd
・{}は以下のように書きましょう！
```
class AAA {
    public void test() {
    }
}

```

2024-09-12 13:25 UTC, NakaU0209 commented on Test2/src/test2/Test2_02.java
> +		System.out.println(a+b);
演算子の両隣には半角スペースを入れましょう！

2024-09-12 13:25 UTC, NakaU0209 commented on Test2/src/test2/Test2_03.java
> +        int a =x;
インデントがおかしいです！

2024-09-13 03:38 UTC, Hiromi0613 commented on Test2/src/test2/Test2_01.java
> +//コンソールに”Hello World!”を表示するプログラムを作成してください
コメントの場所を修正しました。

2024-09-13 03:39 UTC, Hiromi0613 commented on Test2/src/test2/Test2_01.java
> +class Test2_01
・クラスにpublicをつけました。
・クラス、メソッド、メンバ変数にはJavaDocをつけました。
・｛｝の位置を修正しました。
確認の程よろしくお願いいたします。

2024-09-13 03:40 UTC, Hiromi0613 commented on Test2/src/test2/Test2_02.java
> +		System.out.println(a+b);
演算子の両隣に半角スペースを追加しました。

2024-09-13 03:40 UTC, Hiromi0613 commented on Test2/src/test2/Test2_03.java
> +        int a =x;
インデントを修正しました。

2024-09-13 15:11 UTC, NakaU0209 requested changes
レビューしました！
各指摘内容は全体的に確認して修正をお願いします！

2024-09-13 15:11 UTC, NakaU0209 commented on Test2/src/test2/Test2_01.java
> +	public static void main(String[] args){
中括弧の左は半角スペースを入れてください！

2024-09-13 15:11 UTC, NakaU0209 commented on Test2/src/test2/Test2_01.java
> +	 */
メソッドのJavaDocはパラメータも記載してください！

2024-09-13 15:11 UTC, NakaU0209 commented on Test2/src/test2/Test2_04.java
> +public class Test2_04{
中括弧の左隣は半角スペースを入れてください。

2024-09-13 15:11 UTC, NakaU0209 commented on Test2/src/test2/Test2_04.java
> +		x = x*3;
演算子の両隣には半角スペースを入れてください！

2024-09-13 15:11 UTC, NakaU0209 commented on Test2/src/test2/Test2_03.java
> +		System.out.println("xの値は"+ x +"、yの値は"+ y +"です。");
演算子の両隣には半角スペースを入れてください！

2024-09-14 06:58 UTC, Hiromi0613 reviewed
コメントを返信しました。

2024-09-14 06:58 UTC, Hiromi0613 commented on Test2/src/test2/Test2_03.java
> +		System.out.println("xの値は"+ x +"、yの値は"+ y +"です。");
演算子の両隣には半角スペースを入れました。

2024-09-14 06:58 UTC, Hiromi0613 commented on Test2/src/test2/Test2_04.java
> +		x = x*3;
演算子の両隣には半角スペースを入れました。

2024-09-14 06:58 UTC, Hiromi0613 commented on Test2/src/test2/Test2_01.java
> +	public static void main(String[] args){
中括弧の左は半角スペースを入れました。

2024-09-14 06:58 UTC, Hiromi0613 commented on Test2/src/test2/Test2_01.java
> +	 */
メソッドのJavaDocにパラメータの記載も追加しました。

2024-09-14 06:58 UTC, Hiromi0613 commented on Test2/src/test2/Test2_04.java
> +public class Test2_04{
中括弧の左隣に半角スペースを入れました。

2024-09-14 10:14 UTC, NakaU0209 requested changes
レビューしました！

2024-09-14 10:14 UTC, NakaU0209 commented on Test2/src/test2/Test2_01.java
> +public class Test2_01 {
指摘漏れすみません！
クラス名にはアンダースコアは使用しないようにお願いします！

2024-09-14 10:14 UTC, NakaU0209 commented on Test2/src/test2/Test2_04.java
> + 　　*/
JavaDocのインデントがおかしいため修正をお願いします！

2024-09-14 14:27 UTC, Hiromi0613 commented on Test2/src/test2/Test2_04.java
> + 　　*/
JavaDocのインデントを修正しました。

2024-09-14 14:28 UTC, Hiromi0613 commented on Test2/src/test2/Test2_01.java
> +public class Test2_01 {
クラス名を変更しました。

2024-09-14 14:31 UTC, Hiromi0613 reviewed
修正しました。

2024-09-14 21:55 UTC, NakaU0209 requested changes
![LGTM](https://image.lgtmoon.dev/266312)

2024-11-07 15:27 UTC, closed without merging